languageCode = "en-us"
title = "East India Cycling"
baseURL = "/"
theme = "massively"
googleanalytics = "UA-180443036-2"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Cycling holidays across Northeast India, from Assam and Meghalaya to Arunachal Pradesh and the Eastern Himalayas."
  defaultImage = "/images/Cycling in northeast India.jpg"
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false

[languages]
[languages.en]
  languageName = "English"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
